export SHELL := /bin/bash -o pipefail

work_dir ?= $(shell "pwd")

define makefiles_clone
curl --retry 5 --fail --silent --retry-delay 1 \
	https://raw.githubusercontent.com/letsrockthefuture/makefiles/main/bin/clone.sh | \
	bash -s
endef

.PHONY: init
init::
	@$(makefiles_clone)

-include $(work_dir)/.makefiles/Makefile